
trigger:
 branches:
  include:
    - master

pr:
  branches:
    include:
      - master


pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Nunit'
    displayName: 'Nunit Stage'
    jobs:
      - job: 'NunitTest'
        displayName: 'Nunit Test'
        steps:
          - script: echo Hello, world!
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
  - stage: 
    displayName: 'Building Artificat'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn: 'Nunit'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Build Artifact'
        steps:
          - script: echo Building Artifact
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(agent.builddirectory)/s/target'
              Contents: '*.jar'
              TargetFolder: '$(build.artifactstagingdirectory)'
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'