
trigger:
 branches:
  include:
    - master

pr:
  branches:
    include:
      - master


pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: 'Nunit'
    jobs:
      - job: 'NunitTest'
        displayName: 'Nunit Test'
        steps:
          - script: echo Hello, world!
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
  - stage: 
    displayName: 'Building Artificat'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Build Artifact'
        steps:
          - script: echo Building Artifact
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'